# Generated by Django 3.0 on 2019-12-24 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0021_remove_event_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guest',
            name='user',
        ),
    ]
